#!/bin/bash

is_enabled() {
    local id="${1?}"
    enabled=$(
        xinput list-props "$id" |
            grep '\bDevice Enabled\b' | sed 's/.*\(.\)$/\1/'
    )
    # xinput returns 0 for disabled and 1 for enabled, so we invert since we
    # pass on 0
    return "$(( !enabled ))"
}

mapfile -t yubikey_input_ids < <(
    xinput list | grep -i yubikey | sed 's/.*id=\([0-9]\+\).*/\1/'
)

notify=0
[[ $1 == '--notify' ]] && notify=1

if (( "${#yubikey_input_ids[@]}" == 0 )); then
    msg='No Yubikeys found, are they shown by xinput?'
    echo "$msg" >&2
    (( notify )) && notify-send "$msg"
    exit 2
fi

for id in "${yubikey_input_ids[@]}"; do
    if is_enabled "$id"; then
        xinput -disable "$id"
        (( notify )) && notify-send "Disabled Yubikey with id $id"
    else
        xinput -enable "$id"
        (( notify )) && notify-send "Enabled Yubikey with id $id"
    fi
done
