#!/bin/bash

is_enabled() {
    local id="${1?}"
    enabled=$(
        xinput list-props "$id" |
            grep '\bDevice Enabled\b' | sed 's/.*\(.\)$/\1/'
    )
    # xinput returns 0 for disabled and 1 for enabled, so we invert since we
    # pass on 0
    return "$(( !enabled ))"
}

show_help() {
    cat << EOF
Usage: ${0##*/} [-n]

Enable and disable Yubikeys.

    -n          show results using notify-send in addition to stdout
EOF
}

notify=0

while getopts nh opt; do
    case "$opt" in
        'n') notify=1 ;;
        'h')
            show_help
            exit 0
        ;;
        '?')
            show_help >&2
            exit 1
        ;;
    esac
done

mapfile -t yubikey_input_ids < <(
    xinput list | grep -i yubikey | sed 's/.*id=\([0-9]\+\).*/\1/'
)

if (( "${#yubikey_input_ids[@]}" == 0 )); then
    msg='No Yubikeys found, are they shown by xinput?'
    echo "$msg" >&2
    (( notify )) && notify-send "$msg"
    exit 2
fi

for id in "${yubikey_input_ids[@]}"; do
    if is_enabled "$id"; then
        xinput -disable "$id"
        (( notify )) && notify-send "Disabled Yubikey with id $id"
    else
        xinput -enable "$id"
        (( notify )) && notify-send "Enabled Yubikey with id $id"
    fi
done
